export const language = {
	en: {
		aoCore: {
			title: 'AO Core',
			aboutMessage: 'AO Core Message Info',
			storedMessage: 'Stored message',
			unverified: 'Not cryptographically verified',
			introduction: 'A message is a set of named values.',
			introductionDescription:
				'Values can be text, numbers, nested messages, or links to other values. A device determines how a request reads or operates on this message.',
			requestedId: 'Opened ID',
			device: 'Device',
			defaultDevice: 'Default when no device is specified.',
			inlineDevice: 'Inline device definition',
			linkedDevice: 'Device reference; its behavior has not been loaded.',
			role: 'Declared type',
			unknownRole: 'No type declared',
			representation: 'Received representation',
			jsonRepresentation: 'AO JSON (json@1.0)',
			recognizedBy: 'Inspector selected from:',
			evidence: {
				protocol: 'AO protocol metadata',
				variant: 'AO variant',
				device: 'device metadata',
				commitment: 'AO commitment metadata',
				context: 'AO exploration context',
			},
			recognitionExplanation: 'Recognition does not establish authenticity.',
			resolutionTitle: 'How this message is resolved',
			baseTitle: 'Start with a message',
			baseDescription: 'This message provides the base values and its device.',
			requestTitle: 'Apply a request',
			requestDescription:
				'A separate request supplies a path. The device decides how to resolve that path against the base message.',
			resultTitle: 'Receive a result',
			resultDescription:
				'Resolution returns a message or a value. Further path segments can continue from that result.',
			resolutionExplanation:
				'This is an explanation, not an execution trace. The inspector reads the stored message at the opened ID; it does not execute a process or substitute an assignment or computed result.',
			commitments: 'Commitments',
			commitmentsDescription: 'Each commitment describes its own declared coverage and method.',
			commitmentId: 'Declared commitment ID',
			matchesOpenedId: 'Matches the opened ID. This identity has not been verified.',
			verification: 'Local verification',
			verificationStates: { 'not-checked': 'Not checked', unsupported: 'Unsupported commitment device' },
			commitmentDevice: 'Commitment device',
			algorithm: 'Algorithm',
			declaredCommitter: 'Declared committer (unverified)',
			declaredCoverage: 'Declared covered fields',
			notProvided: 'Not provided',
			unsigned: 'Unsigned commitment',
			unsignedExplanation:
				'An HMAC or constant-key commitment does not identify a public signer. Its integrity has not been checked locally.',
			verificationExplanation:
				'These are declarations from the received message. Lunar has not reconstructed the signed representation or verified this commitment, its ID, or its committer.',
			unknownCoverage: 'Coverage unknown',
			emptyCoverage: 'No fields listed',
			linkedCommitments:
				'Commitments are linked. Open commitments+link in Message Fields to view their stored representation.',
			noCommitments:
				'No inline commitments were supplied. This does not prove that the message has no other commitments.',
			fields: 'Message Fields',
			graph: {
				viewMode: 'Message view',
				table: 'Table View',
				view: 'Graph View',
				root: 'Opened message',
				loading: 'Loading graph view…',
				description: 'Expand values to explore messages. Select a coverage count to see its evidence.',
				legend:
					'Solid line: inline value. Dashed line: linked value. This graph shows stored data, not an execution trace.',
				fit: 'Fit view',
				arrange: 'Arrange',
				zoomIn: 'Zoom in',
				zoomOut: 'Zoom out',
				limit: (count: number) => `Showing ${count} cards. Collapse a branch before opening more.`,
				connection: (key: string, linked: boolean) => `${key}: ${linked ? 'linked value' : 'inline value'}`,
				selectCommitment: 'Select a commitment ID to highlight the fields it lists in its message card.',
				highlighted: (id: string) => `Highlight fields listed by ${id}`,
			},
			fieldKey: 'Key',
			fieldType: 'Type',
			fieldCoverage: 'Coverage',
			fieldValue: 'Value',
			fieldTypes: {
				link: 'Link',
				message: 'Message',
				list: 'List',
				text: 'Text',
				integer: 'Integer',
				number: 'Number',
				boolean: 'Boolean',
				null: 'Null',
			},
			typesDescription:
				'Types in the received AO JSON representation. Encoding metadata such as ao-types is retained as a field.',
			coverageDescription:
				'Exact field names listed by each of this message’s inline commitments. Declarations are not cryptographic verification and do not establish coverage of a child message’s fields.',
			coverageStates: { listed: 'Listed (unverified)', 'not-listed': 'Not listed', unknown: 'Unknown' },
			coverageCount: (listed: number, total: number) => `${listed} of ${total} listed`,
			coverageUnknownCount: (count: number) => `${count} unknown`,
			expandCoverage: (key: string) => `Show coverage for ${key || '""'}`,
			collapseCoverage: (key: string) => `Hide coverage for ${key || '""'}`,
			coverageFor: (key: string) => `Commitment coverage for ${key || '""'}`,
			commitmentKind: 'Kind',
			signatureCommitment: 'Signature commitment',
			coverageEvidence: 'Evidence',
			coverageEvidenceDescription:
				'Each row checks this field’s exact key in one commitment’s committed list. Item numbers start at 1, matching the expanded list. No cryptographic verification has been performed.',
			coverageMatch: (position: number, key: string) => `committed · item ${position}: ${key || '""'}`,
			coverageAbsent: (count: number) => `Not in committed (${count} ${count === 1 ? 'item' : 'items'})`,
			coverageUnavailable: 'Unknown: committed list missing or malformed',
			coverageInfo: {
				title: 'About coverage',
				introductionTitle: 'Which commitments include this field?',
				introduction:
					'Coverage shows which commitments declare that they include a particular message field. Lunar compares the field’s exact key with the committed list inside each commitment supplied with this message.',
				commitmentsDescription:
					'A message is a set of named values. A commitment is a separate record describing a method of committing to some of those values. Different commitments can include different fields, and a commitment can be signed or unsigned. Coverage describes that declared scope.',
				labelsTitle: 'How to read the column',
				labels: [
					{
						label: '2 of 3 listed',
						description:
							'This exact key appears in two of the three supplied commitments’ lists. Each commitment counts once. The total includes signed and unsigned commitments; it is not a count of verified signatures or independent signers.',
					},
					{
						label: '1 of 3 listed · 1 unknown',
						description:
							'One commitment lists the key, one has no usable list, and the remaining commitment does not list it. Unknown entries are included in the total but never counted as a match.',
					},
					{
						label: 'Not listed',
						description:
							'All supplied lists are readable, and none includes this exact key. An empty list also lists no fields. This label describes the received lists; it does not prove that no commitment elsewhere could cover the field.',
					},
					{
						label: 'Unknown',
						description:
							'No match can be established because no inline commitments were supplied, or at least one committed list is missing or malformed. A missing list is never interpreted as covering every field.',
					},
				],
				exampleTitle: 'Example: base-hashpath',
				exampleIntroduction: 'Suppose a message includes these three commitments. Their committed lists are:',
				exampleCommitments: [
					{ label: 'Commitment A — signature', fields: '["ao-types", "base-hashpath"]' },
					{ label: 'Commitment B — unsigned', fields: '["ao-types", "base-hashpath"]' },
					{ label: 'Commitment C — signature', fields: '["hashpath"]' },
				],
				exampleConclusion:
					'base-hashpath shows “2 of 3 listed”. It is item 2 in A and B, and absent from C. hashpath would show “1 of 3 listed”. Neither count says that any commitment has been verified.',
				sections: [
					{
						id: 'evidence',
						title: 'Open the evidence',
						paragraphs: [
							'Click a coverage count or status to expand its evidence when inline commitments are available. Each row shows the commitment ID, its declared kind, and the matching list position—or why a match cannot be established.',
							'“committed → item 2: base-hashpath” points to the second value in that commitment’s list. Item numbers start at 1. You can also expand commitments → commitment ID → committed to inspect the original list. Reading coverage does not run a request or execute a process.',
						],
					},
					{
						id: 'verification',
						title: 'Coverage and cryptographic verification',
						paragraphs: [
							'Lunar currently reads declarations from the received message. It has not checked the signature, recomputed the commitment ID, or authenticated the declared signer. A listed field can still belong to an invalid or altered commitment.',
							'Verification would require interpreting the commitment’s device and method, reconstructing the relevant representation, and checking its cryptographic proof. Counting names in committed does not perform those checks. Coverage also does not establish that the returned message matches the opened ID or that a computation or hashpath is correct.',
						],
					},
					{
						id: 'unsigned',
						title: 'Why unsigned commitments count',
						paragraphs: [
							'An unsigned commitment can still declare a list of fields, so it contributes to the coverage count. Lunar labels recognized HMAC or constant-key commitments as unsigned. Such a commitment does not identify a public signer, and Lunar has not checked its integrity.',
							'A signature commitment label means a signature was supplied, not that it is valid. More listed commitments do not automatically mean more trust or more independent endorsements.',
						],
					},
					{
						id: 'children',
						title: 'Links, child messages, and exact keys',
						paragraphs: [
							'This inspector compares the keys in the received AO JSON exactly. For example, body and body+link are different keys for this check. If a list contains body while the table shows body+link, the row is not counted as listed. Interpreting coverage across encodings requires the commitment’s device-specific rules, which this column does not apply.',
							'A child message is checked against its own commitments. Its fields do not inherit the parent’s count. Commitment records and the lists inside them omit the Coverage column so that metadata entries are not confused with the message fields they describe.',
						],
					},
					{
						id: 'scope',
						title: 'Which commitments are included?',
						paragraphs: [
							'The count uses only commitments supplied inline with the current message. Opening commitments+link lets you inspect linked metadata, but does not merge those records into the current message’s counts. Other commitments may exist elsewhere.',
							'Transport headers are separate from the message fields checked here. The node serving the response is also separate from any signer declared by a commitment.',
						],
					},
				],
			},
			inferredDevice: 'default',
			fieldCount: (count: number) => `${count.toLocaleString()} ${count === 1 ? 'field' : 'fields'}`,
			itemCount: (count: number) => `${count.toLocaleString()} ${count === 1 ? 'item' : 'items'}`,
			fieldsPage: (page: number, total: number) => `Page ${page} of ${total}`,
			expandField: (key: string) => `Expand ${key}`,
			collapseField: (key: string) => `Collapse ${key}`,
			childFields: (key: string) => `Fields of ${key}`,
			loadingLink: 'Loading linked value…',
			openLinkedMessage: 'Open linked ID',
			invalidLink: 'This link is not a supported 43-character message ID.',
			cyclicLink: 'This ID is already open in this branch. Open it separately to explore it again.',
			depthLimit: 'This branch has reached the expansion limit. Use the raw message or open the linked ID separately.',
			noFields: 'No fields in this message or list.',
			linkErrors: {
				unavailable: 'The linked value could not be loaded from the configured AO providers.',
				timeout: 'The linked value read timed out. You can retry it.',
				'invalid-response':
					'The provider did not return a supported AO JSON value. The original link is preserved above.',
			},
			provenance: 'Source & raw message',
			provider: 'Served by',
			source: 'Read source',
			configuredPeers: 'Configured AO peers',
			sources: { peers: 'AO peers', permawebos: 'PermawebOS', fallback: 'AO peers (fallback)' },
			identityExplanation:
				'The opened ID is the lookup address. Commitment IDs and hashpaths have separate roles; Lunar has not verified that this response matches the opened ID. Raw JSON retains every received field, including commitments. Transport headers describe the response and are not treated as signed message fields.',
			showRaw: 'Show raw response',
			hideRaw: 'Hide raw response',
			rawMessage: 'Received JSON',
			transportHeaders: 'Transport response headers',
			loading: 'Reading the stored AO message…',
			retry: 'Retry AO read',
			unrecognized: 'This response has no recognized AO metadata. The transaction Overview remains available.',
			errors: {
				unavailable:
					'The configured AO providers could not return this message. Try again or review the AO network settings.',
				timeout: 'The AO read timed out. You can retry the request.',
				'invalid-response':
					'The provider did not return a supported AO JSON message. This inspector accepts message maps up to 4 MiB and 64 levels deep.',
			},
			unindexedTitle: 'No indexed transaction is available',
			unindexedDescription:
				'This ID resolved through the AO network. Open AO Core Info to inspect its message; transaction inclusion and confirmation details are unavailable.',
			unindexedPending:
				'Open AO Core Info for the stored-message read status. Transaction inclusion and confirmation details are unavailable.',
		},
		graphqlTypeDescriptions: {
			SCALAR: 'A single value, such as text, a number, or a boolean.',
			INPUT_OBJECT: 'An input object with the following fields.',
			OBJECT: 'An object with the following fields.',
			ENUM: 'One of the following values.',
			INTERFACE: 'A shared set of fields implemented by the listed object types.',
			UNION: 'A result that can be any of the listed object types.',
		},
		graphqlTypeNoDescription: 'No description is available for this type.',
		graphqlDeprecated: 'Deprecated',
		appDeployment: 'App Deployment',
		blockIndex: 'Block Index',
		arweaveMessagesLoading: 'Loading scheduled messages…',
		arweaveMessagesEmpty: 'No confirmed messages have been scheduled yet.',
		arweaveMessagesError: 'Unable to load scheduled messages. Retry or check Network Settings.',
		arweaveMessagesStale: 'Showing the previous messages. The latest schedule could not be read.',
		processCreation: 'Process creation',
		retry: 'Retry',
		pinned: 'Pinned',
		tabActions: 'Tab actions',
		pinTab: 'Pin Tab',
		unpinTab: 'Unpin Tab',
		pinsEmpty: 'Pin explorer tabs to find them here.',
		pinsStorageError: 'Pins could not be saved in this browser. They are available for this session.',
		pinsLimit: 'You have 200 pinned tabs. Unpin a tab to add another.',
		profileLoading: 'Loading your profile...',
		profileAvatar: 'Profile picture',
		profileBanner: 'Profile banner',
		profileSubmitted: 'Profile transaction submitted. Waiting for indexing.',
		profileIndexed: 'Profile updated.',
		profileStale: 'Showing your saved profile. The latest profile could not be fetched.',
		profilePhases: {
			preparing: 'Preparing profile transaction...',
			'awaiting-wallet': 'Waiting for your wallet...',
			uploading: 'Submitting transaction...',
		},
		profileErrors: {
			'invalid-input': 'Check the profile fields. Images must be PNG, JPEG, GIF, or WebP and at most 10 MB.',
			'invalid-response': 'The profile or wallet response was invalid.',
			unavailable: 'Unable to load or save the profile. Please try again.',
			timeout: 'The profile request timed out. Please try again.',
			cancelled: 'Profile update cancelled.',
			rejected: 'The signature request was declined.',
			'wallet-changed': 'Your wallet account changed. Reopen the profile editor to continue.',
			'wallet-unavailable': 'The wallet could not sign the transaction. Check your wallet and try again.',
			'unknown-outcome': 'The submission could not be confirmed. Check this transaction before submitting again.',
		},
		nodeExplorer: 'Arweave Node',
		nodeVisit: 'Visit Node',
		nodeTabInfo: 'Tab Information',
		nodeMempoolInfo: 'Mempool Information',
		nodeMiningInfo: 'Miner Information',
		nodeMinerFilters: 'Miner Filters',
		nodeSearchInput: 'Enter a node IP or URL',
		nodeTransactionDetailsError: 'Some transaction details are unavailable. Refresh to retry.',
		nodeMempool: 'Mempool',
		nodeShowForkHistory: 'Show Fork History',
		nodeForkHistory: 'Fork History',
		nodeForkHistorySource: 'Reporting Node',
		nodeForkHistoryDescription:
			'Recent forks reported by the selected node, with verified parent links and canonical blocks. Gaps between observed heights are compressed. Scroll to explore branches; select a block to open it.',
		nodeForkHistoryLoading: 'Loading fork history...',
		nodeForkHistoryUnsupported: 'This node does not provide recent fork history.',
		nodeForkStates: {
			chain: 'Current tip',
			history: 'Canonical branch',
			orphan: 'Orphaned',
			context: 'Parent block',
			unknown: 'Unknown parent',
		},
		walletMining: 'Mining',
		walletMiner: 'Miner',
		walletMiningDescription:
			'Block counts and total rewards cover the indexed range from the selected node. All-time mining totals are unavailable. Pending rewards are read live from that node.',
		walletMiningSource: 'Mining Data Source',
		walletMiningNode: 'Reporting Node',
		walletMiningNone: 'No blocks for this miner are present in the local index yet.',
		walletMiningLoading: 'Checking mining activity...',
		walletMiningLookupError: 'Mining activity could not be checked. Retry to refresh pending rewards.',
		walletMiningIndexedRewards: 'Indexed Total Rewards',
		walletMiningIndexedBlocks: 'Indexed Blocks Mined',
		walletMiningChecked: 'Index Updated',

		nodeMiners: 'Miners',
		nodeSummedRewards: 'Total Rewards',
		nodePendingRewards: 'Pending Rewards',
		nodePendingRewardsDescription:
			'Mining rewards currently reserved by this node and not yet available in the spendable balance. This includes rewards outside the indexed range. Unsupported nodes show Unavailable.',
		nodeIndexedRange: 'Indexed Range',
		nodeIndexedBlocks: 'Indexed Blocks',
		nodeBlockRange: 'Block Range',
		nodeStartTime: 'Start Time',
		nodeEndTime: 'End Time',
		nodeMinerBlocks: 'Indexed Blocks Mined',
		nodeViewMinerBlocks: (address: string) => `View indexed blocks mined by ${address}`,
		nodeHideMinerBlocks: (address: string) => `Hide indexed blocks mined by ${address}`,
		nodePage: (page: number) => `Page (${page.toLocaleString()})`,
		nodeBlockHistory: 'Block History',
		nodeRewardsPartial: 'partial',
		nodeRewardsDescription:
			'Total rewards cover claimed mining rewards in the indexed blocks only. Missing reward data is marked as partial; different denominations are shown separately.',
		nodeConfirmedTransactions: 'Indexed Confirmed Transactions',
		nodeTransactionsInfo: 'Transaction Information',
		nodeTransactionsDescription:
			'Confirmed transactions from blocks indexed on this node’s chain, newest blocks first. Each Next click also indexes older blocks in the background when more are available. You can browse indexed pages while a batch loads. Transaction details load for the visible page only.',
		nodeTransactionsLoading: 'Reading confirmed transactions from this node...',
		nodeTransactionsEmpty: 'No confirmed transactions in the indexed blocks.',
		nodeNoChanges: 'No transactions since the previous observation.',
		nodeLoading: 'Reading node status...',
		nodeBlocksLoading: 'Indexing blocks from this node...',
		nodeRecentBlocks: 'Recent Blocks',
		nodeReleaseCommit: 'Release / Git Commit',
		nodeQueue: 'Queue Length',
		nodeStateLatency: 'Node State Latency',
		nodeStoredBlocks: 'Stored Blocks',
		nodeGitCommit: 'Git Commit',
		nodeCurrentBlock: 'Current Block',
		nodeWeaveSize: 'Weave Size',
		nodeBlockHash: 'Block Hash',
		nodeDataSize: 'Data Size',
		nodeReward: 'Reward',
		nodeMiningAddress: 'Mining Address',
		nodeUnclaimed: 'Unclaimed',
		nodePendingTransactions: 'Pending Transactions',
		nodeMempoolDescription:
			'Pending transactions reported by this node. Refreshes every minute while this tab is active. First observed is saved in this browser per node; removed transactions are not necessarily mined.',
		nodeMempoolLoading: 'Refreshing pending transactions...',
		nodeMempoolEmpty: 'No pending transactions reported.',
		nodeMempoolBaseline: 'First read — changes appear after the next successful refresh.',
		nodeMempoolChanges: (added: number, removed: number) =>
			`${added.toLocaleString()} added · ${removed.toLocaleString()} removed since the previous successful read`,
		nodeLastObserved: (date: string) => `Last observed: ${date}`,
		nodeTransactionId: 'Transaction ID',
		nodeContentType: 'Content-Type',
		nodeAppName: 'App-Name',
		nodeAmount: 'Amount',
		nodeFee: 'Fee',
		nodeFirstObserved: 'First Observed',
		nodeAdded: 'Added',
		nodeRemoved: 'Removed',
		nodeChangesLimit: (count: number) => `Showing the first ${count.toLocaleString()} IDs.`,
		nodeIndexedMiners: 'Indexed Mining Addresses',
		nodeRefreshBalances: 'Refresh Balances',
		nodeIndexOlder: (count: number) => `Index ${count} Older Blocks`,
		nodeMiningDescription:
			'All mining addresses found in blocks indexed from this node, saved in this browser across refreshes. Counts, total rewards and last blocks cover the indexed range, not all-time mining. Each Next click also indexes older blocks in the background when more are available, including with a filter applied. You can browse indexed pages while a batch loads. The range also expands when browsing older blocks or confirmed transactions. Balances are current spendable AR; pending rewards are reserved separately.',
		nodeMiningCoverage: (count: number, low: string, high: string) =>
			`${count.toLocaleString()} indexed blocks · heights ${low}–${high}`,
		nodeMiningLimit: (count: number) =>
			`This browser retains up to ${count.toLocaleString()} blocks. Older blocks leave the index as the chain advances.`,
		nodeFindMiner: 'Filter Mining Address',
		nodeNoMinersMatch: 'No indexed mining addresses match this filter.',
		nodeMinersEmpty: 'No mining addresses found in the indexed blocks.',
		nodeBlocksMined: 'Blocks Mined',
		nodeLastBlock: 'Last Block Mined',
		nodeBalanceDescription: 'Current spendable balance on this node. Reserved mining rewards are excluded.',
		nodeRetry: 'Retry',
		nodeStale: 'Showing the last successful observation.',
		nodeErrors: {
			cancelled: 'Request cancelled.',
			timeout: 'This node did not respond in time. Please retry.',
			unavailable: 'Unable to read this node. Please retry.',
			'not-found': 'This node no longer has the requested data.',
			'invalid-input': 'Enter a valid node IP or HTTP(S) URL without a path, query, or credentials.',
			'invalid-response': 'This node returned an invalid response. Please retry.',
			'rate-limited': 'Requests are temporarily rate limited. Please retry shortly.',
			'chain-changed': 'The node’s chain changed during indexing. Refresh to read its current chain.',
		},
		arweaveNodes: 'Arweave Nodes',
		nodesAll: 'All Nodes',
		nodesView: 'Nodes view',
		nodesByFork: 'By Fork',
		nodesFork: (number: number) => `Fork ${number}`,
		nodesSharedAncestor: 'Shared Ancestor',
		nodesUnverifiedTip: 'Unverified Ancestry',
		nodesUnclassified: 'Unclassified',
		nodesTipHeight: (height: string) => `Tip height ${height}`,
		nodesSharedAncestorDescription:
			'These nodes are behind more than one observed branch. Their tip is a shared ancestor, so they do not identify a single fork.',
		nodesUnclassifiedDescription:
			'The node tip is unavailable or has not been checked yet. Continue unchecked nodes or refresh to retry unavailable nodes.',
		nodesUnverifiedDescription:
			'This tip could not yet be compared with every other branch. It is not a confirmed separate fork.',
		nodesCheckingTips: (checked: number, total: number) =>
			`Checking node tips (${checked.toLocaleString()} of ${total.toLocaleString()})...`,
		nodesCheckingAncestry: 'Checking block ancestry...',
		nodesContinueChecks: 'Continue Checking',
		nodesForkChecksPaused: 'Some node tips are still unchecked. Continue checking to include them in the fork groups.',
		nodesRelayInfoSource: 'Node information and response time measured through the arweave.net relay.',
		nodesShowMap: 'Show Map',
		nodesShowTable: 'Show Table',
		nodesLoading: 'Loading nodes, this may take some time...',
		nodesNoReachable: 'No reachable nodes found. Refresh to check again.',
		nodesChecksInterrupted: 'Some node checks could not finish. Refresh to retry.',
		nodesEmpty: 'No nodes found.',
		nodesLoadError: 'Unable to refresh the peer list. Please try again.',
		nodesPage: (page: number, total: number) => `Page (${page} of ${total})`,
		nodesUpdated: (time: string) => `Peer list updated ${time}`,
		nodeEndpoint: 'IP Address / Port',
		nodeVersionRelease: 'Version / Release',
		nodePeers: 'Peers',
		nodeResponseTime: 'Response Time',
		nodeLastChecked: 'Last Checked',
		nodeNotChecked: 'Not checked',
		nodesInfoPaused: 'Node checks are currently unavailable.',
		nodesInfoSource: 'Reachability and response time measured from stats.forward.computer.',
		nodeReachable: 'Reachable',
		nodeUnavailable: 'Unavailable',
		nodeLatency: (ms: string) => `${ms} ms`,
		nodesMapGeoAttribution: 'IP Geolocation by DB-IP',
		nodesMapAnalyticsSource: 'Locations via Analytics',
		nodesMapLabel: 'Approximate locations of Arweave peers',
		nodesMapLoading: 'Loading country locations…',
		nodesMapLoadError: 'Unable to load country locations. Please try again.',
		nodesMapAttribution: (release: string) => `IP Geolocation by DB-IP (${release})`,
		nodesMapProgress: (located: number, total: number) => `${located} of ${total} IP addresses located`,
		nodesMapFailures: (count: number) => `${count} locations unavailable.`,
		nodesMapEmpty: 'No locations available yet.',
		nodesMapRetry: 'Retry Locations',
		action: `Action`,
		addresses: `Addresses`,
		addressesAtBlock: (height: string) => `Block ${height}`,
		addressesLoading: `Loading Addresses...`,
		addressesNotFound: `No addresses with a positive balance found`,
		addANode: `Add a node`,
		addNode: `Add Node`,
		age: `Age`,
		all: `All`,
		amount: `Amount`,
		aoLegacynet: `AO Legacynet`,
		aoMainnet: `AO Mainnet`,
		aoProcess: `AO Process`,
		aoCoreExecutions: `AO Core Executions`,
		aos: `AOS`,
		aosCommand: `AOS Command`,
		aosEditorPlaceholder: `-- AOS Editor`,
		app: `Lunar`,
		appearance: `Appearance`,
		apply: `Apply`,
		applyFilters: `Apply Filters`,
		april: `April`,
		arTransferLoadWarning: `AR transfers may take some time to load.`,
		arm: `ARM`,
		arweave: `Arweave`,
		assignment: `Assignment`,
		associatedMessagesInfo: `Associated messages will display here`,
		associatedMessagesLoading: `Getting associated messages`,
		associatedMessagesNotFound: `No associated messages found`,
		august: `August`,
		authority: `Authority`,
		availableNodes: `Available Nodes`,
		bio: `Bio`,
		balance: `Balance`,
		block: `Block`,
		blockId: `Block ID`,
		blockSize: `Block Size`,
		blockHeightActual: `Block Height`,
		blockHeight: `Scheduled Block Height`,
		blockFilters: `Block Filters`,
		blockOverview: `Block Overview`,
		blocks: `Blocks`,
		blocksLoading: `Loading Blocks...`,
		blocksNotFound: `No blocks found`,
		bundle: `Bundle`,
		bundleFormat: `Bundle Format`,
		bundleOverview: `Bundle Overview`,
		bundler: `Bundler`,
		bundleTags: `Bundle Tags`,
		bundleVersion: `Bundle Version`,
		bundles: `Bundles`,
		cancel: `Cancel`,
		changeConnection: `Change Connection`,
		checking: `Checking`,
		chooseAppAppearance: `Choose Appearance`,
		clear: `Clear`,
		clearAllTabs: 'Clear all tabs',
		clearTabs: `Clear Tabs`,
		clickToCopy: `Click to copy`,
		close: `Close`,
		confirmed: `Confirmed`,
		closeEditor: `Close Editor`,
		collapseExpandAll: `Collapse / Expand All`,
		commandNotSupported: `Command Not Supported`,
		computeInProgress: `Compute In Progress`,
		confirmations: `Confirmations`,
		connect: `Connect`,
		connectToAOS: `Connect to AOS`,
		connectToContinue: `Connect your wallet to continue`,
		connectWallet: `Connect Your Wallet`,
		console: `Console`,
		copied: `Copied`,
		copy: `Copy`,
		copyAddress: `Copy Address`,
		copyFullUrl: `Copy Full URL`,
		copyId: `Copy ID`,
		copyJSON: `Copy JSON`,
		cpuAverage: `CPU Average`,
		create: `Create`,
		createNewProcess: `Create a New Process`,
		createNewTab: 'Create a new tab',
		createProfile: `Create Your Profile`,
		creatingProcess: `Creating Process`,
		current: `Current`,
		currentConnection: `Current Connection`,
		currentOutput: `Current Output`,
		currentRun: `Current Run`,
		currentState: `Current State`,
		customAction: `Custom Action`,
		darkDefault: `Dark Default`,
		darkMuted: `Dark Muted`,
		darkHighContrast: `Dark High Contrast`,
		darkThemes: `Dark themes`,
		data: `Data`,
		date: `Date`,
		dataProtocol: `Data Protocol`,
		dateCreated: `Date Created`,
		dateFilter: `Date Filter`,
		daybreak: `Daybreak`,
		december: `December`,
		delete: `Delete`,
		disconnect: `Disconnect`,
		dismiss: `Dismiss`,
		done: `Done`,
		docs: `Docs`,
		download: `Download`,
		downloadJSON: `Download JSON`,
		eclipse: `Eclipse`,
		edit: `Edit`,
		editProfile: `Edit Your Profile`,
		editorModeNotAvailable: `Editor mode not available in this view`,
		elapsed: `Elapsed`,
		endDate: `End Date`,
		enterFullScreen: `Enter Full Screen`,
		enterProcessName: `Enter Process Name`,
		error: `Error`,
		errorFetching: `Error Fetching`,
		errorFetchingData: `Error Fetching Data`,
		errorFetchingMessageData: `Error Fetching Message Data`,
		errorFetchingResult: `Error Fetching Result`,
		errorFetchingTx: `Error getting transaction`,
		errorGettingResult: `Error Getting Result`,
		errorLog: `Error Log`,
		errorLogEntry: (index: number, time: Date, message: string) =>
			`Error ${index + 1} at ${time.toLocaleTimeString()}: ${message}`,
		errorOccurred: `Error occurred`,
		errorUpdatingProfile: `Error updating profile`,
		executions: `Executions`,
		exitFullScreen: `Exit Full Screen`,
		explorer: `Explorer`,
		explorerSearchInput: `Transaction ID, Wallet Address, Block, or Arweave Node`,
		failedToExecuteQuery: `Failed to execute query`,
		february: `February`,
		fee: `Fee`,
		fetching: `Fetching`,
		filter: `Filter`,
		filterByAction: `Filter By Action`,
		filterByAddress: `Filter By Address`,
		filterByHeight: `Filter By Height`,
		filterByTransfers: `Filter By Transfers`,
		filterByType: `Filter By Type`,
		filterByVariant: `Filter By Variant`,
		friday: `Friday`,
		fridayShort: `Fr`,
		from: `From`,
		fromFilter: (address: string) => `From (${address})`,
		goBack: `Go Back`,
		goTo: `Go To`,
		goToResults: `Go To Results`,
		graphql: `GraphQL`,
		handle: `Handle`,
		healthy: `Healthy`,
		height: `Height`,
		hideResults: `Hide Results`,
		home: `Home`,
		id: `ID`,
		incoming: `Incoming`,
		info: `Info`,
		input: `Input`,
		inspect: `Inspect`,
		invalidJSON: `Invalid JSON`,
		january: `January`,
		july: `July`,
		june: `June`,
		language: `Language`,
		largeResultSetWarning: `Fetching more than 100 results will take some time.`,
		legacynet: `Legacynet`,
		lastTransaction: `Last Transaction`,
		lightDefault: `Light Default`,
		lightMuted: `Light Muted`,
		lightThemes: `Light themes`,
		load: `Load`,
		loading: `Loading`,
		loadingAOS: `Loading AOS...`,
		loadingResult: `Loading Result...`,
		loadMoreItems: (count: number, remaining: number) => `Load ${count} more items (${remaining} remaining)`,
		loadMoreKeys: (count: number, remaining: number) => `Load ${count} more keys (${remaining} remaining)`,
		mainnet: `Mainnet`,
		march: `March`,
		maxCharsReached: `Max chars reached`,
		maxHeight: `Max Height`,
		may: `May`,
		message: `Message`,
		messageFilters: `Message Filters`,
		messageInfo: `Message Info`,
		markedAsSpam: `Marked as Spam`,
		messages: `Messages`,
		midnight: `Midnight`,
		minHeight: `Min Height`,
		miner: `Miner`,
		minerReward: `Miner Reward`,
		module: `Module`,
		monday: `Monday`,
		mondayShort: `Mo`,
		name: `Name`,
		network: `Network`,
		new: `New`,
		newTab: `New Tab`,
		next: `Next`,
		noData: `No Data`,
		noDataToDisplay: `No Data To Display`,
		noErrors: `No errors`,
		noReadsYet: `No reads yet`,
		noVariant: `No Variant`,
		node: `Node`,
		networkSettings: `Network Settings`,
		aosNode: `Compute Node`,
		aosNodeDescription: `Used by the AOS page for process creation, evaluation, and results.`,
		aoReadNetwork: `AO Read Network`,
		aoReadNetworkDescription: `Used for process state, results, and scheduler reads in Explorer.`,
		preferPermawebOS: `Prefer PermawebOS`,
		preferPermawebOSDescription: `Use the extension’s network when available. No wallet connection is required for reads.`,
		fallbackToPeers: `Fall back to peers on failure`,
		fallbackToPeersDescription: `If PermawebOS fails or times out, retry reads through these peers. Try PermawebOS again after one minute.`,
		peerFallbackActive: `PermawebOS failed. Using fallback peers.`,
		permawebOSActive: `Reading through PermawebOS.`,
		peersActive: `Reading through configured peers.`,
		processPeers: `Process state`,
		schedulePeers: `Schedules`,
		linkedStatePeers: `Linked state`,
		managedByPermawebOS: `Managed by PermawebOS`,
		aoPeers: `AO peers`,
		aoPeersDescription: `Separate peer URLs with commas. Used when PermawebOS is unavailable, disabled, or fails with fallback enabled.`,
		invalidAoPeers: `Enter 1–8 HTTPS peer origins separated by commas. HTTP is supported for localhost.`,
		savePeers: `Save peers`,
		resetPeers: `Reset peers`,
		graphqlEndpoint: `GraphQL Endpoint`,
		graphqlEndpointDescription: `Used for every GraphQL query outside the GraphQL page, including search, message lists, blocks and transactions.`,
		graphqlEndpointUrl: `Endpoint URL`,
		invalidGraphqlEndpoint: `Enter a full HTTP or HTTPS GraphQL URL.`,
		saveGraphqlEndpoint: `Save endpoint`,
		resetGraphqlEndpoint: `Reset endpoint`,
		aoReadUnavailable: `Unable to read from the configured AO network. Check the network settings and try again.`,
		aoReadTimeout: `The AO read timed out. Try again or update the peers in network settings.`,
		loadingLinkedState: 'Loading linked values…',
		loadMoreData: 'Load more data',
		moreStateAvailable: 'More state is available to load.',
		aoReadPartial: 'Some state values could not be loaded. Showing the values received so far.',
		aoReadInvalid: `The AO network returned an invalid response.`,
		nodes: `Nodes`,
		none: `None`,
		notYetFound: `Not Yet Found`,
		november: `November`,
		october: `October`,
		offline: `Offline`,
		online: `Online`,
		open: `Open`,
		openEditor: `Open Editor`,
		openInExplorer: `Open in Explorer`,
		openInNewTab: `Open in New Tab`,
		openNetworkSettings: `Open Network Settings`,
		or: `Or`,
		outgoing: `Outgoing`,
		output: `Output`,
		overview: `Overview`,
		owner: `Owner`,
		page: `Page`,
		pageNotFound: `Page not found`,
		pending: `Pending`,
		pageOf: (current: number, total: number) => `Page ${current} of ${total}`,
		performance: `Performance`,
		perPage: (count: number | string) => `${count} per page`,
		pressEnter: `Press Enter`,
		previous: `Previous`,
		previousBlock: `Previous Block`,
		price: `Price`,
		process: `Process`,
		processing: `Processing`,
		processId: `Process ID`,
		processName: `Process Name`,
		processOrMessageTagsInfo: `Process or Message tags will display here`,
		profile: `Profile`,
		profileCreated: `Profile created`,
		profileCreatingInfo: `Creating your profile`,
		profileMenu: `Profile menu`,
		profileUpdated: `Profile updated`,
		profileUpdatingInfo: `Updating your profile`,
		queryVariables: `Query Variables`,
		read: `Read`,
		readFrom: `Read From`,
		readLog: `Read Log`,
		readRequestsHandled: `Read Requests Handled`,
		recentMessages: `Recent Messages`,
		recentBlocks: `Recent Blocks`,
		recentTransactions: `Recent Transactions`,
		recipient: `Recipient`,
		refresh: `Refresh`,
		remove: `Remove`,
		removeAvatar: `Remove Avatar`,
		removeBanner: `Remove Banner`,
		requests: `Requests`,
		response: `Response`,
		result: `Result`,
		resultMessage: `Result Message`,
		resultingMessages: `Resulting Messages`,
		resultingMessagesInfo: `Resulting messages will display here`,
		results: `Results`,
		resultsPerPage: `Results Per Page`,
		roundtripLogEntry: (index: number, time: string, startTime: string) =>
			`(${index + 1}) Roundtrip Time (${time}), Started at ${startTime}`,
		roundtripTime: `Roundtrip Time`,
		run: `Run`,
		runForResponse: `Run to get a response`,
		running: `Running`,
		saturday: `Saturday`,
		saturdayShort: `Sa`,
		save: `Save`,
		savedGateways: `Saved Gateways`,
		scheduler: `Scheduler`,
		schedulerPageSizeLimit: (count: number | string) => `Scheduler mode supports up to ${count} results per page`,
		schedulerType: `Scheduler Type`,
		search: `Search`,
		escapeKey: `ESC`,
		searchProcessId: `Search for Process ID`,
		searching: `Searching`,
		seconds: `Seconds`,
		sender: `Sender`,
		september: `September`,
		settings: `Settings`,
		showFixedNodeStatus: `Show Node Status`,
		showFixedNodeStatusDescription: `Displays the Compute Node in the bottom-right corner of the app.`,
		showResults: `Show Results`,
		showingRange: (start: number, end: number, total: number) => `Showing ${start} - ${end} of ${total}`,
		sidebarClose: `Close sidebar`,
		sidebarOpen: `Open sidebar`,
		size: `Size`,
		slot: `Slot`,
		sortNewestToOldest: `Newest to Oldest`,
		sortOldestToNewest: `Oldest to Newest`,
		source: `Source`,
		startDate: `Start Date`,
		startDateFilter: (date: string) => `Start (${date})`,
		startedAt: `Started at`,
		starting: `Starting`,
		startTime: `Start Time`,
		status: `Status`,
		submit: `Submit`,
		success: `Success`,
		sunday: `Sunday`,
		sundayShort: `Su`,
		sunlit: `Sunlit`,
		syncWithSystem: `Sync With System`,
		syncWithSystemDescription: `Automatically switch between light and dark themes based on your system preferences`,
		systemLoad: `System Load`,
		tabsDeleteConfirmationInfo: `Are you sure you want to clear your tabs ? All persisted transactions will be removed from local storage.`,
		tags: `Tags`,
		target: `Target`,
		themes: `Themes`,
		thursday: `Thursday`,
		thursdayShort: `Th`,
		time: `Time`,
		timestamp: `Timestamp`,
		to: `To`,
		toFilter: (address: string) => `To (${address})`,
		toggleEditor: `Toggle the editor with: (Ctrl + E) or '.editor'`,
		token: `Token`,
		tokenLogo: `Token logo`,
		tokenTransfer: `Token Transfer`,
		top: `Top`,
		transaction: `Transaction`,
		transactionData: `Transaction data`,
		transactionFilters: `Transaction Filters`,
		transactionOverview: `Transaction Overview`,
		txRoot: `TX Root`,
		txCount: `Tx Count`,
		transactions: `Transactions`,
		transactionsLoading: `Loading Transactions...`,
		transactionsNotFound: `No transactions found`,
		transfer: `Transfer`,
		transferFrom: `Transfer From`,
		tuesday: `Tuesday`,
		tuesdayShort: `Tu`,
		txCannotBeFoundYet: `Transaction cannot be found yet`,
		txCannotBeFoundYetInfo: `It may still be propagating or waiting to be indexed. Try refreshing in a moment.`,
		txNotFound: `Transaction not found`,
		type: `Type`,
		unhealthy: `Unhealthy`,
		unknownError: `Unknown error`,
		untitled: `Untitled`,
		updating: `Updating`,
		uploadAvatar: `Upload Avatar`,
		uploadBanner: `Upload Banner`,
		uptime: `Uptime`,
		value: `Value`,
		valueBetween0And100: `Value must be between 0 and 100`,
		valueGreaterThan0: `Value must be greater than 0`,
		variant: `Variant`,
		view: `View`,
		walletAddress: `Wallet Address`,
		wednesday: `Wednesday`,
		wednesdayShort: `We`,
		welcomeToAOS: `Welcome to AOS: Your operating system for AO, the decentralized open access supercomputer.`,
		write: `Write`,
		writeRequestsHandled: `Write Requests Handled`,
		yourProcesses: `Your processes`,
	},
};
