export const language = {
	en: {
		action: `Action`,
		addANode: `Add a node`,
		addNode: `Add Node`,
		amount: `Amount`,
		aoLegacynet: `AO Legacynet`,
		aoMainnet: `AO Mainnet`,
		aoCoreExecutions: `AO Core Executions`,
		aos: `AOS`,
		aosCommand: `AOS Command`,
		aosEditorPlaceholder: `-- AOS Editor`,
		app: `Lunar`,
		appearance: `Appearance`,
		apply: `Apply`,
		applyFilters: `Apply Filters`,
		april: `April`,
		arm: `ARM`,
		associatedMessagesInfo: `Associated messages will display here`,
		associatedMessagesLoading: `Getting associated messages`,
		associatedMessagesNotFound: `No associated messages found`,
		august: `August`,
		authority: `Authority`,
		availableNodes: `Available Nodes`,
		bio: `Bio`,
		blockHeight: `Scheduled Block Height`,
		cancel: `Cancel`,
		changeConnection: `Change Connection`,
		checking: `Checking`,
		chooseAppAppearance: `Choose Appearance`,
		clear: `Clear`,
		clearTabs: `Clear Tabs`,
		clickToCopy: `Click to copy`,
		close: `Close`,
		closeEditor: `Close Editor`,
		collapseExpandAll: `Collapse / Expand All`,
		commandNotSupported: `Command Not Supported`,
		computeInProgress: `Compute In Progress`,
		connect: `Connect`,
		connectToAOS: `Connect to AOS`,
		connectToContinue: `Connect your wallet to continue`,
		connectWallet: `Connect Your Wallet`,
		console: `Console`,
		copied: `Copied`,
		copyAddress: `Copy Address`,
		copyFullUrl: `Copy Full URL`,
		copyId: `Copy ID`,
		copyJSON: `Copy JSON`,
		cpuAverage: `CPU Average`,
		create: `Create`,
		createNewProcess: `Create a New Process`,
		createProfile: `Create Your Profile`,
		creatingProcess: `Creating Process`,
		current: `Current`,
		currentConnection: `Current Connection`,
		currentOutput: `Current Output`,
		currentRun: `Current Run`,
		customAction: `Custom Action`,
		darkDefault: `Dark Default`,
		darkHighContrast: `Dark High Contrast`,
		darkThemes: `Dark themes`,
		data: `Data`,
		date: `Date`,
		dataProtocol: `Data Protocol`,
		dateCreated: `Date Created`,
		dateFilter: `Date Filter`,
		daybreak: `Daybreak`,
		december: `December`,
		delete: `Delete`,
		disconnect: `Disconnect`,
		dismiss: `Dismiss`,
		done: `Done`,
		docs: `Docs`,
		download: `Download`,
		downloadJSON: `Download JSON`,
		eclipse: `Eclipse`,
		edit: `Edit`,
		editProfile: `Edit Your Profile`,
		editorModeNotAvailable: `Editor mode not available in this view`,
		elapsed: `Elapsed`,
		endDate: `End Date`,
		enterFullScreen: `Enter Full Screen`,
		enterProcessName: `Enter Process Name`,
		error: `Error`,
		errorFetching: `Error Fetching`,
		errorFetchingData: `Error Fetching Data`,
		errorFetchingMessageData: `Error Fetching Message Data`,
		errorFetchingResult: `Error Fetching Result`,
		errorFetchingTx: `Error getting transaction`,
		errorGettingResult: `Error Getting Result`,
		errorLog: `Error Log`,
		errorLogEntry: (index: number, time: Date, message: string) =>
			`Error ${index + 1} at ${time.toLocaleTimeString()}: ${message}`,
		errorOccurred: `Error occurred`,
		errorUpdatingProfile: `Error updating profile`,
		executions: `Executions`,
		exitFullScreen: `Exit Full Screen`,
		explorer: `Explorer`,
		explorerSearchInput: `Transaction ID or Wallet Address`,
		failedToExecuteQuery: `Failed to execute query`,
		february: `February`,
		fetching: `Fetching`,
		filter: `Filter`,
		filterByAction: `Filter By Action`,
		filterByAddress: `Filter By Address`,
		friday: `Friday`,
		fridayShort: `Fr`,
		from: `From`,
		fromFilter: (address: string) => `From (${address})`,
		goBack: `Go Back`,
		goTo: `Go To`,
		goToResults: `Go To Results`,
		graphql: `GraphQL`,
		handle: `Handle`,
		healthy: `Healthy`,
		hideResults: `Hide Results`,
		home: `Home`,
		id: `ID`,
		incoming: `Incoming`,
		info: `Info`,
		input: `Input`,
		invalidJSON: `Invalid JSON`,
		january: `January`,
		july: `July`,
		june: `June`,
		language: `Language`,
		legacynet: `Legacynet`,
		lightDefault: `Light Default`,
		lightHighContrast: `Light High Contrast`,
		lightThemes: `Light themes`,
		load: `Load`,
		loading: `Loading`,
		loadingAOS: `Loading AOS...`,
		loadingResult: `Loading Result...`,
		loadMoreItems: (count: number, remaining: number) => `Load ${count} more items (${remaining} remaining)`,
		loadMoreKeys: (count: number, remaining: number) => `Load ${count} more keys (${remaining} remaining)`,
		mainnet: `Mainnet`,
		march: `March`,
		maxCharsReached: `Max chars reached`,
		may: `May`,
		message: `Message`,
		messageFilters: `Message Filters`,
		messageInfo: `Message Info`,
		messageMarkedAsSpam: `Message marked as spam`,
		messages: `Messages`,
		midnight: `Midnight`,
		module: `Module`,
		monday: `Monday`,
		mondayShort: `Mo`,
		name: `Name`,
		network: `Network`,
		new: `New`,
		newTab: `New Tab`,
		next: `Next`,
		noData: `No Data`,
		noDataToDisplay: `No Data To Display`,
		noErrors: `No errors`,
		noReadsYet: `No reads yet`,
		noVariant: `No Variant`,
		node: `Node`,
		nodeConfiguration: `Node Configuration`,
		nodes: `Nodes`,
		none: `None`,
		november: `November`,
		october: `October`,
		offline: `Offline`,
		online: `Online`,
		open: `Open`,
		openEditor: `Open Editor`,
		openInNewTab: `Open in New Tab`,
		or: `Or`,
		outgoing: `Outgoing`,
		output: `Output`,
		overview: `Overview`,
		owner: `Owner`,
		page: `Page`,
		pageNotFound: `Page not found`,
		pageOf: (current: number, total: number) => `Page ${current} of ${total}`,
		performance: `Performance`,
		perPage: (count: number | string) => `${count} per page`,
		pressEnter: `Press Enter`,
		previous: `Previous`,
		price: `Price`,
		processing: `Processing`,
		processId: `Process ID`,
		processName: `Process Name`,
		processOrMessageTagsInfo: `Process or Message tags will display here`,
		profile: `Profile`,
		profileCreated: `Profile created`,
		profileCreatingInfo: `Creating your profile`,
		profileMenu: `Profile menu`,
		profileUpdated: `Profile updated`,
		profileUpdatingInfo: `Updating your profile`,
		queryVariables: `Query Variables`,
		read: `Read`,
		readLog: `Read Log`,
		readRequestsHandled: `Read Requests Handled`,
		recentMessages: `Recent Messages`,
		recipient: `Recipient`,
		refresh: `Refresh`,
		remove: `Remove`,
		removeAvatar: `Remove Avatar`,
		removeBanner: `Remove Banner`,
		requests: `Requests`,
		response: `Response`,
		result: `Result`,
		resultMessage: `Result Message`,
		resultingMessages: `Resulting Messages`,
		resultingMessagesInfo: `Resulting messages will display here`,
		results: `Results`,
		resultsPerPage: `Results Per Page`,
		roundtripLogEntry: (index: number, time: string, startTime: string) =>
			`(${index + 1}) Roundtrip Time (${time}), Started at ${startTime}`,
		roundtripTime: `Roundtrip Time`,
		run: `Run`,
		runForResponse: `Run to get a response`,
		running: `Running`,
		saturday: `Saturday`,
		saturdayShort: `Sa`,
		save: `Save`,
		savedGateways: `Saved Gateways`,
		scheduler: `Scheduler`,
		search: `Search`,
		searchProcessId: `Search for Process ID`,
		searching: `Searching`,
		seconds: `Seconds`,
		sender: `Sender`,
		september: `September`,
		settings: `Settings`,
		showResults: `Show Results`,
		showingRange: (start: number, end: number, total: number) => `Showing ${start} - ${end} of ${total}`,
		sidebarClose: `Close sidebar`,
		sidebarOpen: `Open sidebar`,
		size: `Size`,
		sortNewestToOldest: `Newest to Oldest`,
		sortOldestToNewest: `Oldest to Newest`,
		source: `Source`,
		startDate: `Start Date`,
		startDateFilter: (date: string) => `Start (${date})`,
		startedAt: `Started at`,
		starting: `Starting`,
		startTime: `Start Time`,
		status: `Status`,
		submit: `Submit`,
		success: `Success`,
		sunday: `Sunday`,
		sundayShort: `Su`,
		sunlit: `Sunlit`,
		syncWithSystem: `Sync With System`,
		syncWithSystemDescription: `Automatically switch between light and dark themes based on your system preferences`,
		systemLoad: `System Load`,
		tabsDeleteConfirmationInfo: `Are you sure you want to clear your tabs ? All persisted transactions will be removed from local storage.`,
		tags: `Tags`,
		target: `Target`,
		themes: `Themes`,
		thursday: `Thursday`,
		thursdayShort: `Th`,
		time: `Time`,
		timestamp: `Timestamp`,
		to: `To`,
		toFilter: (address: string) => `To (${address})`,
		toggleEditor: `Toggle the editor with: (Ctrl + E) or '.editor'`,
		token: `Token`,
		tokenLogo: `Token logo`,
		tokenTransfer: `Token Transfer`,
		top: `Top`,
		transactionData: `Transaction data`,
		transferFrom: `Transfer From`,
		tuesday: `Tuesday`,
		tuesdayShort: `Tu`,
		txNotFound: `Transaction not found`,
		type: `Type`,
		unhealthy: `Unhealthy`,
		unknownError: `Unknown error`,
		untitled: `Untitled`,
		updating: `Updating`,
		uploadAvatar: `Upload avatar`,
		uploadBanner: `Upload banner`,
		uptime: `Uptime`,
		valueBetween0And100: `Value must be between 0 and 100`,
		variant: `Variant`,
		view: `View`,
		walletAddress: `Wallet Address`,
		wednesday: `Wednesday`,
		wednesdayShort: `We`,
		welcomeToAOS: `Welcome to AOS: Your operating system for AO, the decentralized open access supercomputer.`,
		write: `Write`,
		writeRequestsHandled: `Write Requests Handled`,
		yourProcesses: `Your processes`,
	},
};
