import { DefaultTheme } from 'styled-components';

const common = {
	positive1: '#42A392',
	caution1: '#D2934E',
	negative1: '#B95B80',
	negative2: '#B7577D',
	dark1: '#151515',
	dark2: '#333333',
	light1: '#FFFFFF',
	light2: '#EAEAEA',
	light3: '#C2C2C2',
	light: {
		overlay1: 'rgb(0, 0, 0, .45)',
		overlay2: 'rgb(0, 0, 0, .5)',
		shadow1: 'rgb(220, 220, 220, .05)',
	},
	dark: {
		overlay1: 'rgb(0, 0, 0, .65)',
		overlay2: 'rgb(0, 0, 0, .5)',
		shadow1: 'rgb(0, 0, 0, .35)',
	},
	actions: {
		eval: '#52A79E',
		info: '#AC78B3',
		balance: '#7889D8',
		transfer: '#D2934E',
		creditNotice: '#42A392',
		debitNotice: '#BC568F',
		mint: '#52A79E',
		piDelegationRecords: '#D2934E',
		reportMint: '#AC78B3',
		setPiIndexWeights: '#42A392',
		saveDelegationSummary: '#D2934E',
		nextPiDelegationPage: '#7889D8',
		none: '#373744',
		other: '#6D74CB',
	},
	editorLight: {
		primary: '#D64B6F',
		alt1: '#2D9984',
		alt2: '#6D74CB',
		alt3: '#1E9368',
		alt4: '#2A72D5',
		alt5: '#6864A6',
		alt6: '#E36A43',
		alt7: '#E2B03A',
		alt8: '#317AAF',
		alt9: '#8CB05D',
		alt10: '#3a3a3a',
	},
	editorDark: {
		primary: '#CA83D4',
		alt1: '#73B3A8',
		alt2: '#5AB4A3',
		alt3: '#6BC9B4',
		alt4: '#78BCB5',
		alt5: '#918DD0',
		alt6: '#E2B03A',
		alt7: '#E2B03A',
		alt8: '#8BB8DE',
		alt9: '#5CB283',
		alt10: '#BCBCBC',
	},
};

export const lightTheme = {
	scheme: 'light',
	neutral1: '#FFFFFF',
	neutral2: '#fbfbfb',
	neutral3: '#eeeeee',
	neutral4: '#D6D6D6',
	neutral5: '#CCCCCC',
	neutral6: '#ADADAD',
	neutral7: '#A3A3A3',
	neutral8: '#8F8F8F',
	neutral9: '#858585',
	neutralA1: '#151515',
	neutralA2: '#333333',
	neutralA3: '#3D3D3D',
	neutralA4: '#474747',
	neutralA5: '#525252',
	neutralA6: '#666666',
	neutralA7: '#707070',
	primary1: '#6D74CB',
	primary2: '#545bbb',
	link1: '#3A7DC7',
	link2: '#4A8AD0',
	editor: { ...common.editorLight },
	...common,
	...common.light,
};

export const lightThemeAlt1 = {
	scheme: 'light',
	neutral1: '#FFFFFF',
	neutral2: '#F9F9F9',
	neutral3: '#F0F0F0',
	neutral4: '#E4E4E4',
	neutral5: '#D6D6D6',
	neutral6: '#CCCCCC',
	neutral7: '#ADADAD',
	neutral8: '#A3A3A3',
	neutral9: '#8F8F8F',
	neutralA1: '#151515',
	neutralA2: '#333333',
	neutralA3: '#3D3D3D',
	neutralA4: '#474747',
	neutralA5: '#525252',
	neutralA6: '#666666',
	neutralA7: '#707070',
	primary1: '#DB5461',
	primary2: '#D43545',
	link1: '#3A7DC7',
	link2: '#4A8AD0',
	editor: { ...common.editorLight },
	...common,
	...common.light,
};

export const lightThemeAlt2 = {
	scheme: 'light',
	neutral1: '#FFFFFF',
	neutral2: '#F9F9F9',
	neutral3: '#F0F0F0',
	neutral4: '#E4E4E4',
	neutral5: '#D6D6D6',
	neutral6: '#CCCCCC',
	neutral7: '#ADADAD',
	neutral8: '#A3A3A3',
	neutral9: '#8F8F8F',
	neutralA1: '#151515',
	neutralA2: '#333333',
	neutralA3: '#3D3D3D',
	neutralA4: '#474747',
	neutralA5: '#525252',
	neutralA6: '#666666',
	neutralA7: '#707070',
	primary1: '#5AB6A0',
	primary2: '#4BAA94',
	link1: '#3A8FA8',
	link2: '#4A99B2',
	editor: { ...common.editorLight },
	...common,
	...common.light,
};

export const lightThemeAlt3 = {
	scheme: 'light',
	neutral1: '#f7f5f3',
	neutral2: '#f2f0ee',
	neutral3: '#e8e6e3',
	neutral4: '#dedad6',
	neutral5: '#c8c4c0',
	neutral6: '#b0aca7',
	neutral7: '#989490',
	neutral8: '#7e7a75',
	neutral9: '#65615c',
	neutralA1: '#3a3835',
	neutralA2: '#4a4845',
	neutralA3: '#5a5855',
	neutralA4: '#6a6865',
	neutralA5: '#2a2825',
	neutralA6: '#8a8680',
	neutralA7: '#9a9690',
	primary1: '#7880c5',
	primary2: '#6670b8',
	link1: '#6A8FC2',
	link2: '#7A99CA',
	editor: { ...common.editorLight },
	...common,
	...common.light,
};

export const darkTheme = {
	scheme: 'dark',
	neutral1: '#171717',
	neutral2: '#1a1a1a',
	neutral3: '#292929',
	neutral4: '#3D3D3D',
	neutral5: '#9B9B9B',
	neutral6: '#949494',
	neutral7: '#626262',
	neutral8: '#6E6E6E',
	neutral9: '#7A7A7A',
	neutralA1: '#F6F6F6',
	neutralA2: '#E8E8E8',
	neutralA3: '#D8D8D8',
	neutralA4: '#C4C4C4',
	neutralA5: '#bababa',
	neutralA6: '#929292',
	neutralA7: '#767676',
	primary1: '#6D74CB',
	primary2: '#545bbb',
	link1: '#5697d5',
	link2: '#498bca',
	editor: { ...common.editorDark },
	...common,
	...common.dark,
};

export const darkThemeAlt1 = {
	scheme: 'dark',
	neutral1: '#16161c',
	neutral2: '#18181f',
	neutral3: '#23242A',
	neutral4: '#282930',
	neutral5: '#3f414d',
	neutral6: '#34353C',
	neutral7: '#3A3B42',
	neutral8: '#404148',
	neutral9: '#47484F',
	neutralA1: '#F9F9F9',
	neutralA2: '#E4E4E4',
	neutralA3: '#D6D6D6',
	neutralA4: '#CCCCCC',
	neutralA5: '#CFCFCF',
	neutralA6: '#8F8F8F',
	neutralA7: '#707070',
	primary1: '#DB5461',
	primary2: '#D43545',
	link1: '#6AA8E0',
	link2: '#5A9AD2',
	...common,
	...common.dark,
	editor: {
		primary: '#ff83a6',
		alt1: '#A3DEE2',
		alt2: '#B9B8D0',
		alt3: '#7cc3db',
		alt4: '#6CB9D9',
		alt5: '#8886D9',
		alt6: '#FFBD9F',
		alt7: '#A8DDE2',
		alt8: '#F2A9D3',
		alt9: '#6D909E',
		alt10: '#BFBFBF',
	},
	actions: {
		eval: '#7EB3B9',
		info: '#918DA4',
		balance: '#5F53AD',
		transfer: '#CF9070',
		creditNotice: '#5A9AAF',
		debitNotice: '#C47AA7',
		mint: '#82B3B9',
		piDelegationRecords: '#CF9070',
		reportMint: '#918DA4',
		setPiIndexWeights: '#5A9AAF',
		saveDelegationSummary: '#CF9070',
		nextPiDelegationPage: '#5F53AD',
		none: '#33353B',
		other: '#4C8EAD',
	},
};

export const darkThemeAlt2 = {
	scheme: 'dark',
	neutral1: '#17191f',
	neutral2: '#191c23',
	neutral3: '#262834',
	neutral4: '#2E2F34',
	neutral5: '#3c3e4c',
	neutral6: '#41424b',
	neutral7: '#52545F',
	neutral8: '#4D4F57',
	neutral9: '#36363F',
	neutralA1: '#F9F9F9',
	neutralA2: '#E4E4E4',
	neutralA3: '#D6D6D6',
	neutralA4: '#CCCCCC',
	neutralA5: '#CFCFCF',
	neutralA6: '#8F8F8F',
	neutralA7: '#707070',
	primary1: '#5AB6A0',
	primary2: '#4BAA94',
	link1: '#4AB5C8',
	link2: '#5ABFCA',
	editor: { ...common.editorDark },
	...common,
	...common.dark,
};

export const darkThemeAlt3 = {
	scheme: 'dark',
	neutral1: '#17181C',
	neutral2: '#1a1b20',
	neutral3: '#2C2D32',
	neutral4: '#2E2F35',
	neutral5: '#3b3b49',
	neutral6: '#464750',
	neutral7: '#51525C',
	neutral8: '#5B5C66',
	neutral9: '#656670',
	neutralA1: '#F9F9F9',
	neutralA2: '#E4E4E4',
	neutralA3: '#D6D6D6',
	neutralA4: '#CCCCCC',
	neutralA5: '#CDCDCD',
	neutralA6: '#8F8F8F',
	neutralA7: '#707070',
	primary1: '#6D74CB',
	primary2: '#545bbb',
	link1: '#8ABEEF',
	link2: '#7AB2E5',
	editor: { ...common.editorDark },
	...common,
	...common.dark,
};

export const theme = (currentTheme: any, id?: string): DefaultTheme => ({
	id,
	scheme: currentTheme.scheme,
	colors: {
		accordion: {
			background: currentTheme.neutral1,
			hover: currentTheme.neutral2,
			color: currentTheme.neutralA1,
		},
		actions: {
			eval: currentTheme.actions.eval,
			info: currentTheme.actions.info,
			balance: currentTheme.actions.balance,
			transfer: currentTheme.actions.transfer,
			debitNotice: currentTheme.actions.debitNotice,
			creditNotice: currentTheme.actions.creditNotice,
			mint: currentTheme.actions.mint,
			piDelegationRecords: currentTheme.actions.piDelegationRecords,
			reportMint: currentTheme.actions.reportMint,
			setPiIndexWeights: currentTheme.actions.setPiIndexWeights,
			saveDelegationSummary: currentTheme.actions.saveDelegationSummary,
			nextPiDelegationPage: currentTheme.actions.nextPiDelegationPage,
			none: currentTheme.actions.none,
			other: currentTheme.actions.other,
		},
		border: {
			primary: currentTheme.neutral3,
			alt1: currentTheme.neutral7,
			alt2: currentTheme.neutral8,
			alt3: currentTheme.neutral9,
			alt4: currentTheme.neutralA5,
			alt5: currentTheme.primary1,
			alt6: currentTheme.primary2,
			alt7: currentTheme.dark1,
		},
		button: {
			primary: {
				background: currentTheme.neutral2,
				border: currentTheme.neutral3,
				color: currentTheme.neutralA1,
				active: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral4,
					color: currentTheme.neutralA1,
				},
				disabled: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral3,
					color: currentTheme.neutral7,
				},
			},
			alt1: {
				background: currentTheme.primary1,
				border: currentTheme.primary1,
				color: currentTheme.light1,
				active: {
					background: currentTheme.primary2,
					border: currentTheme.primary2,
					color: currentTheme.light1,
				},
				disabled: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral3,
					color: currentTheme.neutral7,
				},
			},
			alt2: {
				background: currentTheme.neutralA1,
				border: currentTheme.neutralA1,
				color: currentTheme.neutral1,
				active: {
					background: currentTheme.neutralA4,
					border: currentTheme.neutralA4,
					color: currentTheme.neutral1,
				},
				disabled: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral3,
					color: currentTheme.neutral7,
				},
			},
		},
		checkbox: {
			active: {
				background: currentTheme.primary1,
			},
			background: currentTheme.neutral1,
			hover: currentTheme.neutral3,
			disabled: currentTheme.neutral5,
		},
		container: {
			primary: {
				background: currentTheme.neutral1,
				active: currentTheme.neutral3,
			},
			alt1: {
				background: currentTheme.neutral2,
			},
			alt2: {
				background: currentTheme.neutral3,
			},
			alt3: {
				background: currentTheme.neutral4,
			},
			alt4: {
				background: currentTheme.neutral5,
			},
			alt5: {
				background: currentTheme.neutral7,
			},
			alt6: {
				background: currentTheme.primary1,
			},
			alt7: {
				background: currentTheme.neutralA3,
			},
			alt8: {
				background: currentTheme.dark2,
			},
			alt9: {
				background: currentTheme.primary1,
			},
			alt10: {
				background: currentTheme.primary2,
			},
			alt11: {
				background: currentTheme.dark1,
			},
		},
		contrast: {
			background: currentTheme.dark2,
			border: currentTheme.dark2,
			color: currentTheme.light1,
			active: {
				background: currentTheme.dark1,
				border: currentTheme.dark2,
				color: currentTheme.light1,
			},
		},
		font: {
			primary: currentTheme.neutralA1,
			alt1: currentTheme.neutralA5,
			alt2: currentTheme.neutralA6,
			alt3: currentTheme.neutral8,
			alt4: currentTheme.neutral1,
			alt5: currentTheme.primary1,
			light1: currentTheme.light1,
			light2: currentTheme.light2,
			light3: currentTheme.light3,
			dark1: currentTheme.dark1,
			dark2: currentTheme.dark2,
		},
		form: {
			background: currentTheme.neutral1,
			border: currentTheme.neutral3,
			invalid: {
				outline: currentTheme.negative1,
				shadow: currentTheme.shadow1,
			},
			valid: {
				outline: currentTheme.primary1,
				shadow: currentTheme.shadow1,
			},
			disabled: {
				background: currentTheme.neutral2,
				border: currentTheme.neutral3,
				label: currentTheme.neutralA2,
			},
		},
		gradient: {
			start: currentTheme.primary1,
			middle: currentTheme.primary1,
			end: currentTheme.primary2,
		},
		icon: {
			primary: {
				fill: currentTheme.neutralA4,
				active: currentTheme.neutral3,
				disabled: currentTheme.neutral7,
			},
			alt1: {
				fill: currentTheme.neutral4,
				active: currentTheme.neutral5,
				disabled: currentTheme.neutral3,
			},
			alt2: {
				fill: currentTheme.neutralA1,
				active: currentTheme.neutralA4,
				disabled: currentTheme.neutral3,
			},
			alt3: {
				fill: currentTheme.neutralA2,
				active: currentTheme.neutral1,
				disabled: currentTheme.neutral3,
			},
		},
		indicator: {
			active: currentTheme.positive1,
		},
		link: {
			color: currentTheme.link1,
			active: currentTheme.link2,
		},
		loader: {
			primary: currentTheme.primary1,
		},
		overlay: {
			primary: currentTheme.overlay1,
			alt1: currentTheme.overlay2,
		},
		editor: { ...currentTheme.editor },
		row: {
			active: {
				background: currentTheme.neutral3,
				border: currentTheme.neutral2,
			},
			hover: {
				background: currentTheme.neutral2,
			},
		},
		scrollbar: {
			track: currentTheme.neutral2,
			thumb: currentTheme.neutral4,
		},
		shadow: {
			primary: currentTheme.shadow1,
		},
		status: {
			draft: currentTheme.caution1,
			published: currentTheme.positive1,
		},
		tabs: {
			color: currentTheme.neutralA4,
			active: {
				background: currentTheme.primary1,
				color: currentTheme.neutralA1,
			},
		},
		view: {
			background: currentTheme.neutral1,
		},
		warning: {
			primary: currentTheme.negative1,
			alt1: currentTheme.negative2,
			caution: currentTheme.caution1,
		},
	},
	typography: {
		family: {
			primary: `'DM Sans', sans-serif`,
			alt1: `'DM Sans', sans-serif`,
			alt2: `'Source Code Pro', serif`,
		},
		size: {
			xxxxSmall: '11px',
			xxxSmall: '12px',
			xxSmall: '13px',
			xSmall: '14px',
			small: '15px',
			base: '16px',
			lg: '18px',
			xLg: '24px',
			xxLg: '28px',
			xxxLg: 'clamp(28px, 2.25vw, 36px)',
			h1: 'clamp(36px, 3.5vw, 56px)',
			h2: 'clamp(32px, 3.25vw, 50px)',
			h4: 'clamp(28px, 3vw, 42px)',
		},
		weight: {
			light: '200',
			regular: '300',
			medium: '400',
			bold: '500',
			xBold: '600',
		},
	},
});
